config/routes.rb
Rails.application.routes.draw do

  devise_for :users ,controllers: {registrations: "registrations", sessions: "sessions"}
  root to: 'markets#marketplace'

  get 'welcome', to: 'public#welcome'
  match "/auth/:provider/callback" => "auth_callback#callback", :via => [:get, :post]
  namespace :social_auth do
     resources :users 
  end
  match "market" => "markets#marketplace", via: [:get]
  match "search" => "markets#search", via: [:get]
  match "initial_results" => "markets#initial_results", via: [:get]
  match "shops/:permalink" => "shops#show", via: [:get]
  namespace :seller do
    resources :shops do
      get :my_bids, on: :collection
      get :inventory
      get :open_bids
      get :past_purchases
      resource :comments do
        get :search, on: :collection
      end
      resources :products do
        put :image_upload, on: :member 
      end
      resources :purchases do
        put :shipped, on: :member 
      end
    end
    resources :wholesale
  end
  resources :feedbacks
  resources :products do
    get :search, on: :collection
    get :for_shop, on: :collection
    get :wholesale, on: :collection
  end

  resources :shops do
    resources :comments
  end

  resources :shoping_carts do
    get :payed, on: :member
    post :add_to_cart, on: :collection
    get :current_cart, on: :collection
    get :checkout, on: :collection 
    delete :remove_purchase, on: :collection
  end

  namespace :platform do
    resources :shops do
      get :search, on: :collection
      get :purchases, on: :member
      get :users, on: :member
      post :assign_shop, on: :member
      get :search_user, on: :member
      resources :bills do
        get :payed, on: :member
      end
      resources :products do
        put :image_upload, on: :member
      end
    end
    resource :dashboard do
      get :feedbacks, on: :collection
    end
  end
  devise_scope :user do
    get 'get_location', to: 'sessions#get_location'
    post 'set_location', to: 'sessions#set_location'
  end
  resource :shopper do
    get :shopping_list, on: :member
    get :wholesale, on: :collection
  end

  resources :bids do
    put :accept, on: :member
  end

  resources :subscriptions do
    get :payed
  end

end

app/controllers/shoppers_controller.rb
class ShoppersController < ApplicationController
  def shopping_list
  	@shopping_carts = current_user.shoping_carts.select{|cart| cart.purchases.map(&:payed).uniq == [true]}  
  end

  def wholesale
  	render 'wholesale'
  end
end

app/views/shoppers/shopping_list.html.haml
%h2
  Purchase history

- @shopping_carts.each do |cart|
  .shoping-cart-history
    %table.table
      %th
        purchased date
      %th
        item
      %th
        shop
      %th
        shipped
      %th
        Contact number
      %th
        Address
        
      - cart.purchases.each  do |purchase|
        %tr
          %td=purchase.created_at.strftime("%Y/%m/%d")
          %td=purchase.product.name
          %td=link_to purchase.shop.name, shop_path(purchase.shop)
          %td=purchase.shiped ? 'Shipped' : 'pending'
          %td=purchase.shop.phone_number
          %td=raw purchase.shop.address.gsub(/\n/, '<br />')
  %br