config/routes.rb
Rails.application.routes.draw do

  devise_for :users ,controllers: {registrations: "registrations", sessions: "sessions"}
  root to: 'markets#marketplace'

  get 'welcome', to: 'public#welcome'
  match "/auth/:provider/callback" => "auth_callback#callback", :via => [:get, :post]
  namespace :social_auth do
     resources :users 
  end
  match "market" => "markets#marketplace", via: [:get]
  match "search" => "markets#search", via: [:get]
  match "initial_results" => "markets#initial_results", via: [:get]
  match "shops/:permalink" => "shops#show", via: [:get]
  namespace :seller do
    resources :shops do
      get :my_bids, on: :collection
      get :inventory
      get :open_bids
      get :past_purchases
      resource :comments do
        get :search, on: :collection
      end
      resources :products do
        put :image_upload, on: :member 
      end
      resources :purchases do
        put :shipped, on: :member 
      end
    end
    resources :wholesale
  end
  resources :feedbacks
  resources :products do
    get :search, on: :collection
    get :for_shop, on: :collection
    get :wholesale, on: :collection
  end

  resources :shops do
    resources :comments
  end

  resources :shoping_carts do
    get :payed, on: :member
    post :add_to_cart, on: :collection
    get :current_cart, on: :collection
    get :checkout, on: :collection 
    delete :remove_purchase, on: :collection
  end

  namespace :platform do
    resources :shops do
      get :search, on: :collection
      get :purchases, on: :member
      get :users, on: :member
      post :assign_shop, on: :member
      get :search_user, on: :member
      resources :bills do
        get :payed, on: :member
      end
      resources :products do
        put :image_upload, on: :member
      end
    end
    resource :dashboard do
      get :feedbacks, on: :collection
    end
  end
  devise_scope :user do
    get 'get_location', to: 'sessions#get_location'
    post 'set_location', to: 'sessions#set_location'
  end
  resource :shopper do
    get :shopping_list, on: :member
    get :wholesale, on: :collection
  end

  resources :bids do
    put :accept, on: :member
  end

  resources :subscriptions do
    get :payed
  end

end

app/models/shop.rb
class Shop < ActiveRecord::Base
  default_scope { where('deleted = false') }
  
  has_attached_file :banner, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/missing_banner.jpg"
  
  validates_attachment_content_type :banner, content_type: /\Aimage\/.*\z/
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :address, presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :phone_number, presence: true, numericality: { only_integer: true }
  validates :pincode, presence: true, numericality: { only_integer: true }
  has_many :products
  has_many :purchases
  has_many :shoping_carts
  belongs_to :user
  before_save :set_permalink
  has_many :comments

  acts_as_geolocated
  
  def to_param
    permalink
  end
  
  def set_permalink
  	self.permalink = self.name.underscore
  end
end

app/controllers/platform/shops_controller.rb
class Platform::ShopsController < PlatformController
  before_action :set_shop, only: [:purchases, :edit, :destroy, :show, :update, :users, :assign_shop, :search_user]
  def purchases
    
    @purchases = @shop.purchases.where(payed: true, payed_out: false, shiped: true)
  end

  def show
    @products = @shop.products
  end
  def index
    @shops = ::Shop.joins(:purchases).
            where(purchases:{payed_out: false, payed: true, shiped: true}).
            group('shops.name', 'shops.id').
            select('shops.name as name, count(purchases.id) as purchase_count, shops.id as id, shops.permalink as permalink')

    @all_shops = Shop.all.limit(10)
    @shop_count = Shop.count
    
  end

  def search
    @all_shops = Shop.where("name LIKE '%#{params[:query]}%'")
    render 'shops', layout: false
  end
  def new
    @shop = Shop.new
    render 'new'
  end
  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      redirect_to platform_shops_path
    else
      render 'new'
    end
  end
  def edit
    render 'edit'
  end

  def update
    if @shop.update_attributes(shop_params)
      redirect_to platform_shop_products_path(@shop)
    else 
      render 'edit'
    end
  end
  def destroy
    @shop.update_attributes(deleted: true)
    redirect_to platform_shops_path
  end

  def users
    @users = User.limit(10).all
    render 'users'
  end
  def assign_shop
    @shop.user_id = params[:user_id]
    @shop.save
    redirect_to users_platform_shop_path(@shop)
  end

  def search_user
    @users = User.where("name LIKE '%#{params[:query]}%' ")
    render 'users_search_result', layout: false
  end
  protected
  def shop_params
    params.require(:shop).permit(:name,:description,:phone_number, :email, :pincode, :lat, :lng, :banner)
  end
  def set_shop
    @shop = ::Shop.find_by_permalink(params[:id])
  end
end

app/controllers/seller/comments_controller.rb
class Seller::CommentsController < Seller::ShopsController
	before_action :set_shop
	def search

		@comments = @shop.comments.where(
			params[:query].split(' ').map{|search_term|
				"text like '%#{search_term}%'"
			}.join(' AND ')
		)
		render 'seller/shops/comments', layout: false
	end
end

app/controllers/seller/products_controller.rb
class Seller::ProductsController < Seller::ShopsController
  before_action :set_shop
  before_action :set_product, only: [:show, :update, :edit, :destroy, :image_upload]
  def new
    @product = Product.new
    @product.shop_id = @shop.id
    render 'seller/shops/products/new'
  end

  def index
    @products = @shop.products.order('created_at DESC').map{ |product|
        product_attributes(product)
    }
    render 'seller/shops/products/index'
  end

  def create
    @product = Product.new(product_params)
    @product.shop_id = @shop.id
    if @product.save
      render json: product_attributes(@product).to_json
    else
      render json: @product.errors.messages
      .map{|field, errors|  [field, errors.join(', ')]}.to_h, status: 422
    end
  end

  def edit
    render 'seller/shops/products/edit'
  end

  def destroy
    @product.update_attributes deleted: true
    render nothing: true, status: :ok
  end
  def image_upload
    @product.update_attributes(product_image_params)
    render json: {image_url: @product.image.url(:medium)}.to_json
  end
  def update
    if @product.update_attributes(product_params)
      render nothing: true, status: :ok
    else
      render json: @product.errors.messages
      .map{|field, errors|  [field, errors.join(', ')]}.to_h, status: 422
    end
  end
  protected
  def set_shop
    @shop = current_user.shops.find_by_permalink(params[:shop_id])
  end
  def product_image_params
    params.permit(:image)
  end
  def set_product
    @product = @shop.products.find(params[:id])
  end
  def product_params
    params.require(:product).permit(:name, :description, :price, :unit, :deliverable, :quantity)
  end
end

app/controllers/seller/purchases_controller.rb
class Seller::PurchasesController < Seller::ShopsController
	before_action :set_shop
	def index
		@purchases = @shop.purchases.where(payed: true).where(categories[filter_params[:filter]|| :new_purchases])
		
		render 'seller/shops/purchases/index'
	end

	def shipped
		purchase = @shop.purchases.find(params[:id])
		if purchase.update_attributes(shiped: true)
			render nothing: true, head: :ok
		else
			render head: 422
		end

	end

	protected

	def set_shop
		@shop = current_user.shops.find_by_permalink(params[:shop_id])
	end
	def filter_params
		params.permit(:filter)
	end

	def categories
	   {
	   	    new_purchases: {payed: true, payed_out: false, shiped: false},
	   	    shiped_purchases: {payed: true, shiped: true, payed_out: false}
	
	   	}.with_indifferent_access
	end
end

app/controllers/seller/shops_controller.rb
class Seller::ShopsController < SellerController
  before_action :set_shop, only: [:edit, :update, :show]
  before_action :set_current_shop, only: [:inventory, :past_purchases, :open_bids]
  before_action :check_subscription, only: :inventory
  def new
    @shop = Shop.new
    @shop.user_id = current_user.id
  end

  def index
    @shops = current_user.shops
  end

  def show
  	@new_purchases = @shop.purchases.where(payed: true, payed_out: false)
    @new_purchases_count = @new_purchases.count - (Rails.cache.fetch("#{current_user.id}_last_seen_product_count").to_i)
    Rails.cache.write("#{current_user.id}_last_seen_product_count", @new_purchases.count)
    @credit = BillValueCalculator.calculate(@new_purchases, true).round(2)
    @undelivered_products = @shop.purchases.where(payed: true, shiped: false).count
    @comments = @shop.comments.order('created_at DESC').limit(10)
  end

  def my_bids
    @product_bids = current_user.bids.joins(:product).order('accepted_at DESC')
    @new_accepted_bid_count = current_user.bids.accepted.count - Rails.cache.fetch("#{current_user.id}/last_seen_accepted_bid_count").to_i
    Rails.cache.write("#{current_user.id}/last_seen_accepted_bid_count", current_user.bids.accepted.count)
  end

  def inventory
    @products = @shop.products.order('created_at DESC').map{ |product|
        product_attributes(product)
    }
  end

  def open_bids
    @product_bids = ::Bid.not_accepted.last_on_top.where(product_id: @shop.products.pluck(:id))
    @new_bid_count = @product_bids.count - (Rails.cache.fetch("#{current_user.id}/last_seen_bid_count").to_i)
    Rails.cache.write("#{current_user.id}/last_seen_bid_count", @product_bids.count)
  end

  def past_purchases
    @product_bids = ::Bid.accepted.order('accepted_at DESC').where(product_id: @shop.products.pluck(:id))
  end

  def edit
    
  end

  def create
  	@shop = Shop.new(shop_params)
  	@shop.user_id = current_user.id
  	if @shop.save
  	  redirect_to seller_shops_path
  	else
  	  render 'new'
  	end
  end

  def update
    if @shop.update_attributes(shop_params)
      redirect_to seller_shop_inventory_path
    else 
      render 'edit'
    end

  end

  def destroy
    @shop.update_attributes(deleted: true)
    @shop.products.update_all(deleted: true)
  end
  protected
  def set_shop
    @shop = current_user.shops.find_by_permalink(params[:id])
  end

  def set_current_shop
    @shop = current_user.shops.find_by_permalink(params[:shop_id])
  end

  layout 'shop'
  private

  def check_subscription
    subscription = current_user.subscription
    if current_user.usertype != "admin" && have_accepted_bids && !Time.now.between?(subscription.start_time, subscription.end_time)
      render 'subscribe_link', layout: false
    end
  end

  def have_accepted_bids
    Action.where(user_id: current_user.id, action_type: 'accept_bid').count > 0
  end

  def shop_params
  	params.require(:shop).permit(:name,:description,:phone_number, :email, :address, :pincode, :lat, :lng, :banner)
  end
end

app/controllers/seller/wholesale_controller.rb
class  Seller::WholesaleController < Seller::ShopsController
	before_action :set_shop
	def index
		render 'wholesale'
	end
end

app/controllers/seller_controller.rb
class SellerController < ApplicationController
  layout 'seller'

  protected
  def product_attributes(product)
    {
      name: product.name,
      price: product.price,
      description: product.description,
      shop_id: product.shop_id,
      image_filename: product.image.original_filename,
      image_url: product.image.url(:medium),
      unit: product.unit,
      id: product.id,
      update_url: seller_shop_product_path(@shop, product),
      image_uploaded: product.image.present?,
      image_upload_url:  image_upload_seller_shop_product_path(@shop, product),
      delete_url:  seller_shop_product_path(@shop, product),
      deliverable: product.deliverable,
      quantity: product.quantity
    }
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :new, :create]
  def show
  	@comment = Comment.new
  	@comments = @shop.comments.order('created_at DESC')
  end
  protected
  def set_shop
  	@shop = Shop.where(permalink: params[:permalink]).first
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
  def new_bids_count
    product_bids = ::Bid.not_accepted.last_on_top.where(product_id: @shop.products.pluck(:id))
    new_bid_count = product_bids.count - Rails.cache.fetch("#{current_user.id}/last_seen_bid_count").to_i
    return new_bid_count
  end

  def new_accepted_bid_count
  	current_user.bids.accepted.count - Rails.cache.fetch("#{current_user.id}/last_seen_accepted_bid_count").to_i
  end
end

app/views/seller/shops/_form_fields.html.haml
= f.input :name
= f.input :description
= f.input :banner, as: :file
= f.input :phone_number
= f.input :email
= f.input :address
= f.input :pincode
= f.input :lat, label: "latitude"
= f.input :lng, label: "longitude"
- if false
  Get your credentials by signing up
  = link_to "instamojo", "https://www.instamojo.com"
  You will get the keys from
  = link_to "here", "https://www.instamojo.com/integrations"

  = f.input :instamajo_api_key, label: "Private API Key"
  = f.input :instamajo_auth_token, label: "Private Auth Token"
= f.submit

= render partial: '/seller_geolocation'

app/views/seller/shops/_profile_sub_nav.html.haml
.shop-attributes
  = @shop.name
  %br
  = @shop.address.gsub('\n', '<br />')
  %br
  = @shop.phone_number
  %br
  = link_to "edit", edit_seller_shop_path(@shop)
.profile-sub-nav
  = link_to seller_shop_inventory_path(@shop) do
    .profile-sub-nav-item{class: action_name == 'inventory' ? "current-profile-item" : ''}
      = "Inventory"
  = link_to seller_shop_open_bids_path(@shop) do
    .profile-sub-nav-item{class: action_name == 'open_bids' ? "current-profile-item" : ''}
      = "Open Bids(#{new_bids_count})"
  = link_to seller_shop_past_purchases_path(@shop) do
    .profile-sub-nav-item{class: action_name == 'past_purchases' ? "current-profile-item" : ''}
      = "Past Purchases"
  .clearfix

app/views/seller/shops/_shops_header.html.haml
.profile-sub-nav
  = link_to seller_shops_path do
    .profile-sub-nav-item{class: action_name == 'index' ? 'current-profile-item' : ''}  
      ="Shops"
  = link_to my_bids_seller_shops_path do
    .profile-sub-nav-item{class: action_name == 'my_bids' ? 'current-profile-item' : ''}
      = "My Bids(#{new_accepted_bid_count})"
  .clearfix

app/views/seller/shops/comments.html.haml
- @comments.each do |comment|
  .feedback-container
    .author
      =comment.user.try(:name)
    .comment-body
      = comment.text

app/views/seller/shops/edit.html.haml
.seller-form-container
  = simple_form_for [:seller, @shop], url:  seller_shop_path  do |f|
    = render partial: 'form_fields',locals: { f: f}

app/views/seller/shops/index.html.haml
= render partial: 'shops_header'
.shops-container
  - if @shops.blank?
    .no-shops-message
      You haven't created any shops. 
      = link_to "Create a shop", new_seller_shop_path
      and start selling your products  
  - @shops.each do |shop|
    .shop-tile-wrapper.pull-left
      .shop-tile.pull-left.col-xs-12.col-sm-6.col-md-4.col-lg-3
        = link_to seller_shop_inventory_path(shop) do
          .shop-banner
            - if shop.banner.present?
              = image_tag shop.banner.url(:medium)
            - else
              = image_tag 'missing_banner'
          %h4.shop-details
            = shop.name
          .shop-details
            = raw(shop.address.gsub("\n", '<br />'))
  .clearfix

app/views/seller/shops/inventory.html.haml
= render partial: 'profile_sub_nav'
.inventory  
  = react_component 'SellerProducts', {products: @products, create_product_url:  seller_shop_products_path }

app/views/seller/shops/my_bids.html.haml
= render partial: 'shops_header'
.my-bids-container
  - bid_count = 0
  - @product_bids.each do |bid|
    - bid_count += 1
    = render partial: '/bids/bid', locals: {bid: bid, public: false, seller: false, past_purchases: false, new_bid: bid_count <= @new_accepted_bid_count}
  - if @product_bids.count == 0
    .no-items-message
      Yoy haven't made any bids

app/views/seller/shops/new.html.haml
.seller-form-container
  = simple_form_for [:seller, @shop], url: seller_shops_path(@shop) do |f|
    = render partial: 'form_fields',locals: { f: f}

app/views/seller/shops/open_bids.html.haml
= render partial: 'profile_sub_nav'
.open-bids-container
  - bid_count = 0
  - @product_bids.each do |bid|
    - bid_count += 1
    = render partial: '/bids/bid', locals: {bid: bid, public: false, seller: true, past_purchases: false,  new_bid: @new_bid_count >= bid_count}

  - if @product_bids.count == 0
    .no-items-message
      No bids have been made to your products

app/views/seller/shops/past_purchases.html.haml
= render partial: 'profile_sub_nav'
.past-purchases-container
  - @product_bids.each do |bid|
    = render partial: '/bids/bid', locals: {bid: bid, public: false, seller: true, past_purchases: true,  new_bid: false}
  - if @product_bids.count == 0  
    .no-items-message
      You haven't accepted any bids

app/views/seller/shops/show.html.haml
.status.pull-left
  .shop-property
    .shop-property-name.pull-left
      New Purchases
    .shop-property-value.pull-right
      = @new_purchases_count
    .clearfix

  .shop-property
    .shop-property-name.pull-left
      Credit
    .shop-property-value.pull-right
      = @credit
    .clearfix
  .shop-property
    .shop-property-name.pull-left
      Undelivered products
    .shop-property-value.pull-right
      = @undelivered_products
    .clearfix
.feedbacks.pull-left
  %h3
    Feedbacks
  .form-group
    search
    %input.form-control.search-comments{data:{search_url: search_seller_shop_comments_path(@shop)}}
  .comment-search-results
    = render template: 'seller/shops/comments'