config/routes.rb
Rails.application.routes.draw do

  devise_for :users ,controllers: {registrations: "registrations", sessions: "sessions"}
  root to: 'markets#marketplace'

  get 'welcome', to: 'public#welcome'
  match "/auth/:provider/callback" => "auth_callback#callback", :via => [:get, :post]
  namespace :social_auth do
     resources :users 
  end
  match "market" => "markets#marketplace", via: [:get]
  match "search" => "markets#search", via: [:get]
  match "initial_results" => "markets#initial_results", via: [:get]
  match "shops/:permalink" => "shops#show", via: [:get]
  namespace :seller do
    resources :shops do
      get :my_bids, on: :collection
      get :inventory
      get :open_bids
      get :past_purchases
      resource :comments do
        get :search, on: :collection
      end
      resources :products do
        put :image_upload, on: :member 
      end
      resources :purchases do
        put :shipped, on: :member 
      end
    end
    resources :wholesale
  end
  resources :feedbacks
  resources :products do
    get :search, on: :collection
    get :for_shop, on: :collection
    get :wholesale, on: :collection
  end

  resources :shops do
    resources :comments
  end

  resources :shoping_carts do
    get :payed, on: :member
    post :add_to_cart, on: :collection
    get :current_cart, on: :collection
    get :checkout, on: :collection 
    delete :remove_purchase, on: :collection
  end

  namespace :platform do
    resources :shops do
      get :search, on: :collection
      get :purchases, on: :member
      get :users, on: :member
      post :assign_shop, on: :member
      get :search_user, on: :member
      resources :bills do
        get :payed, on: :member
      end
      resources :products do
        put :image_upload, on: :member
      end
    end
    resource :dashboard do
      get :feedbacks, on: :collection
    end
  end
  devise_scope :user do
    get 'get_location', to: 'sessions#get_location'
    post 'set_location', to: 'sessions#set_location'
  end
  resource :shopper do
    get :shopping_list, on: :member
    get :wholesale, on: :collection
  end

  resources :bids do
    put :accept, on: :member
  end

  resources :subscriptions do
    get :payed
  end

end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
	def marketplace

	end

	def search
		lat,lng = params[:geolocation][1..-1].split(', ').map(&:to_f)
		term = params[:term]
		quantity = params[:quantity]
		page = params[:page]
		results = ShopSearch.new(lat, lng, term, quantity, page).results
		render json: with_bid_path(results)
	end

	def initial_results
		lat,lng = params[:geolocation][1..-1].split(', ').map(&:to_f)
		page = params[:page]
		results = ShopSearch.new(lat, lng, nil, nil, page).results
		render json: with_bid_path(results)
	end

	layout 'shop'

	protected

	def with_bid_path(products)
    products.map do |product|
      product.attributes.merge(bid_path: new_bid_path(product_id: product.id))
    end
	end
end

app/views/markets/marketplace.html.haml
.market-left.pull-left
  .search
    = form_tag search_path, method: :get, class: 'search-form', remote: true do
      = label_tag "Search for"
      .clearfix
      = text_field_tag :term
      .clearfix
      = label_tag "Quantity needed"
      .clearfix
      = number_field_tag :quantity
      .clearfix
      = label_tag "Near"
      .clearfix
      = text_field_tag :place
      .clearfix
      = hidden_field_tag :geolocation, "(#{session[:lat]}, #{session[:lng]})"
      = hidden_field_tag :page, 1
      = button_tag type: :submit, class: 'search_button' do
        = "Search"
        %i.fa.fa-search
  #map
  #existing-bids.modal
    .existing-bids.modal-sm
.market-right.pull-left
  .filter-links.pull-right
    filter
    .fa.fa-th.filter-grid
    .fa.fa-align-justify.filter-row.current-filter
  .clearfix
  .result-row-view
    .results-headder
      .results-headder-item.pull-left
        Item
      .results-headder-item.pull-left
        Distance
      .results-headder-item.pull-left
        Rate (Per Kg)
      .results-headder-item.pull-left
        Total
      .clearfix
    .results-body{data:{results_per_page: ShopSearch::RESULTS_PER_PAGE}}
      .results-wait
        = image_tag 'giphy.gif'
  .result-grid-view.hidden
  .load-more-button.hidden{data: {page: 1}}
    = "Load more"